# Generated by Django 5.2.5 on 2025-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foconeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile')),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('session_duration', models.IntegerField(null=True)),
            ],
        ),
    ]
